workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Zillow Property Extended Search API:
        inputs:
            - location: openapi.yml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/adityaprakash-work/client-packages/zillow-property-extended-search-api
targets:
    zillow-rapidapi-client:
        target: python
        source: Zillow Property Extended Search API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/adityaprakash-work/client-packages/zillow-property-extended-search-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
