openapi: 3.1.0
info:
  title: Zillow Property Extended Search API
  description: API for searching properties using various filters.
  version: 1.0.0
servers:
  - url: https://zillow-com1.p.rapidapi.com
    description: RapidAPI Zillow Proxy
paths:
  /propertyExtendedSearch:
    get:
      summary: Search for properties
      operationId: propertyExtendedSearch
      parameters:
        - name: location
          in: query
          description: Location details (address, county, neighborhood, or Zip code). Required if polygon or coordinates are empty.
          schema:
            type: string
            maxLength: 100
        - name: page
          in: query
          description: Page number for paginated results. Max value is 20.
          schema:
            type: integer
            maximum: 20
        - name: status_type
          in: query
          description: Property status type.
          schema:
            type: string
            enum:
              - ForSale
              - RecentlySold
              - ForRent
        - name: home_type
          in: query
          description: Property type. Comma-separated list.
          schema:
            type: string
            enum:
              - Houses
              - Apartments_Condos_Co-ops
              - Multi-family
              - Apartments
              - Manufactured
              - Condos
              - LotsLand
              - Townhomes
        - name: sort
          in: query
          description: Sorting order.
          schema:
            type: string
            enum:
              - Homes_for_You
              - Price_High_Low
              - Price_Low_High
              - Newest
              - Bedrooms
              - Bathrooms
              - Square_Feet
              - Lot_Size
        - name: minPrice
          in: query
          description: Minimum price filter.
          schema:
            type: number
        - name: maxPrice
          in: query
          description: Maximum price filter.
          schema:
            type: number
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PropertySearchResponse"
        "400":
          description: Bad request
        "500":
          description: Internal server error
      x-speakeasy-group: properties
      x-speakeasy-name-override: search
components:
  schemas:
    PropertySearchResponse:
      type: object
      properties:
        props:
          type: array
          items:
            $ref: "#/components/schemas/Property"
        resultsPerPage:
          type: integer
        totalPages:
          type: integer
        totalResultCount:
          type: integer
        currentPage:
          type: integer
    Property:
      type: object
      properties:
        dateSold:
          type: string
          format: date-time
          nullable: true
        propertyType:
          type: string
          enum:
            - SINGLE_FAMILY
            - MULTI_FAMILY
            - CONDO
            - TOWNHOUSE
            - APARTMENT
            - LAND
        lotAreaValue:
          type: number
        address:
          type: string
        imgSrc:
          type: string
          format: uri
        price:
          type: number
        bedrooms:
          type: integer
        longitude:
          type: number
        latitude:
          type: number
        listingStatus:
          type: string
          enum:
            - FOR_SALE
            - PENDING
            - SOLD
        zpid:
          type: string
        listingSubType:
          type: object
          properties:
            is_FSBA:
              type: boolean
        daysOnZillow:
          type: integer
        bathrooms:
          type: number
        livingArea:
          type: integer
        country:
          type: string
        currency:
          type: string
        lotAreaUnit:
          type: string
        hasImage:
          type: boolean
